# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
        def setupUi(self, Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(600, 360)
                Dialog.setMinimumSize(QtCore.QSize(600, 360))
                self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 581, 80))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
                font = QtGui.QFont()
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("background-color: rgb(219, 253, 230);")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.horizontalLayout.addWidget(self.label_2)
                self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
                font = QtGui.QFont()
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setStyleSheet("background-color: rgb(219, 253, 230);")
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.horizontalLayout.addWidget(self.label)
                self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 249, 581, 101))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.registercustomerbut = QtWidgets.QPushButton(self.gridLayoutWidget)
                self.registercustomerbut.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "")
                self.registercustomerbut.setObjectName("registercustomerbut")
                self.registercustomerbut.clicked.connect(self.p)
                self.gridLayout.addWidget(self.registercustomerbut, 0, 1, 1, 1)
                self.logincustomerbut = QtWidgets.QPushButton(self.gridLayoutWidget)
                self.logincustomerbut.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "")
                self.logincustomerbut.setObjectName("logincustomerbut")
                self.gridLayout.addWidget(self.logincustomerbut, 0, 0, 1, 1)
                self.loginsellerbut = QtWidgets.QPushButton(self.gridLayoutWidget)
                self.loginsellerbut.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(255, 255, 255);")
                self.loginsellerbut.setObjectName("loginsellerbut")
                self.gridLayout.addWidget(self.loginsellerbut, 1, 0, 1, 1)
                self.registersellerbut = QtWidgets.QPushButton(self.gridLayoutWidget)
                self.registersellerbut.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(255, 255, 255);")
                self.registersellerbut.setObjectName("registersellerbut")
                self.gridLayout.addWidget(self.registersellerbut, 1, 1, 1, 1)
                self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
                self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 581, 81))
                self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
                font = QtGui.QFont()
                font.setFamily("Script MT Bold")
                font.setPointSize(36)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setAlignment(QtCore.Qt.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.verticalLayout.addWidget(self.label_3)

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
                self.label_2.setText(_translate("Dialog", "|Login as|"))
                self.label.setText(_translate("Dialog", "|Register as|"))
                self.registercustomerbut.setText(_translate("Dialog", "Customer"))
                self.logincustomerbut.setText(_translate("Dialog", "Customer"))
                self.loginsellerbut.setText(_translate("Dialog", "Seller"))
                self.registersellerbut.setText(_translate("Dialog", "Seller"))
                self.label_3.setText(_translate("Dialog", "Welcome to Online Shop"))

        def p(self):
                print('ok')



if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
