# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        Dialog.setBaseSize(QtCore.QSize(600, 400))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 561, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(219, 253, 230);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 220, 561, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userline = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.userline.setStyleSheet("borde-radius:30%;\n"
"border-color: rgb(110, 147, 161);\n"
"")
        self.userline.setObjectName("userline")
        self.verticalLayout_2.addWidget(self.userline)
        self.passline = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.passline.setStyleSheet("borde-radius:30%;\n"
"border-color: rgb(110, 147, 161);\n"
"")
        self.passline.setObjectName("passline")
        self.verticalLayout_2.addWidget(self.passline)
        self.enter = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enter.setFont(font)
        self.enter.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.enter.setObjectName("enter")
        self.verticalLayout_2.addWidget(self.enter)
        self.success = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.success.setFont(font)
        self.success.setAlignment(QtCore.Qt.AlignCenter)
        self.success.setObjectName("success")
        self.verticalLayout_2.addWidget(self.success)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.enter.clicked.connect(self.loginaccount)

    mark = False

    def loginaccount(self):
        username = self.userline.text()
        password = self.passline.text()
        user = open("database.txt", "r")
        user = user.readlines()
        user = [u.replace('\n', '').split() for u in users]
        for i in range(len(user)):
            if username == user[i][0] and password == user[i][1]:
                mark = True
                print("success")
        if mark == False:
            print('username or password invalid!')


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login to your account"))
        self.enter.setText(_translate("Dialog", "Enter"))
        self.success.setText(_translate("Dialog", "login was successful"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
